# Generated by Django 3.0.5 on 2020-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='feito',
            field=models.BooleanField(default='False'),
        ),
    ]
